### ISSUE TITLE
large smilies break the smilie window

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#17]
the @chrishansen69 smilies break the smilie window and make it hard to navigate

**Comment by cravxx** [comment]
raf pls

**Comment by cravxx** [comment]
temp. removed. resize and uncomment if u feel like it

**Comment by uwx** [comment]
kk

**Comment by uwx** [comment]
is 80px enough

**Comment by cravxx** [comment]
80px is a general guideline you can see sizes of the ones that are in there just follow that
