### ISSUE TITLE
fix retarded versioning system

### ISSUE THREAD

**Issue by uwx** [HulaSamsquanch/aimgames#18]
kaff pls

**Comment by cravxx** [comment]
okkk

**Comment by uwx** [comment]
GOD DAMMIT
major.minor.hotfix
1.2.3
1.4.0
DON'T ADD ANOTHER CHARACTER TO THE DAMN NUMBER FOR EVERY LITTLE THING YOU DO AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by cravxx** [comment]
OK FINE

**Comment by uwx** [comment]
i'll make a bot to do it...eventually

**Comment by cravxx** [comment]
actually i didnt mean to reopen this lol. but ok
