### ISSUE TITLE
make alive actually do something

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#20]

**Comment by cravxx** [comment]
vision: 
This is purely a prototype at the moment, but in the last five minutes I've thought of a lot of good ideas for it. This will be a more complex project than Swearify. This script is actually (partially) written using jQuery, something which Swearify will also be "updated" to shortly. 

I do not recommend installing at the moment, as it is completely useless, but definitely keep an eye on this page for updates.

## Features:
- An overlay that pretends to accomplish something but really doesn't
- A "scrolling" notification system. This will come in handy once I implement it right...

### Working on:
- Notifications for when a member comes online
- Ability to send PMs, and access a memebers contact info (eg. Skype name)

**Comment by uwx** [comment]
user contact page
http://aimgames.forummotion.com/uIDcontact
PM user
http://aimgames.forummotion.com/privmsg?mode=post&u=ID
skype
skype:SKYPENAME?call
(use my url getter)
email
http://aimgames.forummotion.com/profile?mode=email&u=ID
website (div)
field_id-10 > dd > .field_uneditable

**Comment by uwx** [comment]
my ideas for alive:
- dubs (already in but not enabled)
- "new msg" ticker/ribbon on the top left corner of the screen (already in)
- hover over someone's username for basic profile info (nothing yet)

edit: i have moved these ideas to a script of my own (chatbox++)

**Comment by cravxx** [comment]
yay it does something. seppuko.
