### ISSUE TITLE
filters swears inside links

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#21]
ruining the link

**Comment by uwx** [comment]
this would need [url=][/url] tags to be fixed

**Comment by cravxx** [comment]
This issue was moved to HulaSamsquanch/swearify#1

**Comment by cravxx** [comment]
partially fixed 263b6ea7353afca8dd835cd5a8e0ca48a6848a59

**Comment by cravxx** [comment]
good enough
