### ISSUE TITLE
"fu" is not detected

### ISSUE THREAD

**Issue by uwx** [HulaSamsquanch/aimgames#3]

**Comment by cravxx** [comment]
regex will no doubt fix this

**Comment by uwx** [comment]
commit #22 fixes this but not completely

**Comment by cravxx** [comment]
This issue was moved to HulaSamsquanch/swearify#6

**Comment by cravxx** [comment]
fu turns into fu$3 now

wtf

**Comment by uwx** [comment]
FIXED
