### ISSUE TITLE
ff addon - lots of shit is broken

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#35]
- Charcount
- Presumably all function associated with posting
- post_page_editor() doesn't run

**Comment by uwx** [comment]
i'll see about it...fuk

**Comment by uwx** [comment]
the nope train to nopeville goes nopenopenopenope

**Comment by uwx** [comment]
since you can't even install the chrome/ff extensions without the browser crying SECCUUURITTTYYYYYY i think this is ded
