### ISSUE TITLE
use Karma to test

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#41]
i wanna use something like this

http://karma-runner.github.io/0.13/index.html

to do testing on multiple platforms and work out some bugs.

**Comment by chrishansen69** [comment]
ISNT THE POINT OF TESTING THAT YOU DO IT ON THE SYSTEM THAT BREAKS

ALSO THAT SITE USES AN IMAGE OF AN EMBEDDED YOUTUBE VIDEO
http://i.imgur.com/zUk38W9.png

**Comment by cravxx** [comment]
Ok, Travis does about as much as we'll need, so this is closed.
