### ISSUE TITLE
get custom smilies into other smilie windows

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#5]
theres two places, the WYSIWYG window and the preview page window

**Comment by uwx** [comment]
the swearify menu appears but no smileys are shown

**Comment by cravxx** [comment]
yes sherlock

**Comment by cravxx** [comment]
This issue was moved to HulaSamsquanch/swearify#4

**Comment by cravxx** [comment]
bump.

**Comment by cravxx** [comment]
done
