### ISSUE TITLE
Spoilers in chat break dubs

### ISSUE THREAD

**Issue by uwx** [HulaSamsquanch/aimgames#59]
halp

**Comment by cravxx** [comment]
Haven't worked on bugs yet; I've been working on this god-forsaken thing: 069bf5b

Figured it might be nice to have a way to clear off spam. But I'll work on issues with Chatbox++ tomorrow.

**Comment by uwx** [comment]
> Haven't worked on bugs yet; I've been working on this god-forsaken thing: 069bf5b

Oooooh, that seems nice! I assume its purpose is to hide posts you don't want to see?

**Comment by uwx** [comment]
no longer a valid issue in chatbox++ v2
