### ISSUE TITLE
Swearify Chrome issues

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#67]
- Braille feature is broken
- Emoticons don't appear in the smilie window (Chrome doesn't support innerHTML) _#5 is somewhat similar_

**Comment by uwx** [comment]
> Braille feature is broken

just escape the characters...?

> Emoticons don't appear in the smilie window (Chrome doesn't support innerHTML) _#5 is somewhat similar_

I'll fix it soon(tm)  
Remember, though, that innerHTML is [off the holy W3C standards](http://www.webdeveloper.com/forum/showthread.php?220145-is-innerHTML-a-W3C-standard&s=27dbb4a8bea4e8a5eba0052087889dd5&p=1049011#post1049011), malpractice<sup>[[1]](http://stackoverflow.com/a/395055)[[2]](http://stackoverflow.com/a/395072)</sup> and a lot slower<sup>[[1]](http://stackoverflow.com/a/11854965)[[2]](http://www.quirksmode.org/dom/innerhtml.html)</sup> than [Document.createTextNode](https://developer.mozilla.org/pt-BR/docs/Web/API/Document/createTextNode) and [Document.createElement](https://developer.mozilla.org/pt-BR/docs/Web/API/Document/createElement). You can also use [Node.textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent).

**Comment by cravxx** [comment]
Currently closed for lack of demand.
