### ISSUE TITLE
Use GitHub Pages instead of RawGit

### ISSUE THREAD

**Issue by uwx** [HulaSamsquanch/aimgames#74]
Rawgit's CDN caches a lot, which makes it harder to edit things.

**Comment by cravxx** [comment]
Noted. Although, I won't be editing this much anymore, unless I for some reason feel like it.

**Comment by uwx** [comment]
Not done yet, fam (I'll set up swearify to pull from github.io instead of RawGit. Appveyor will handle the rest)

**Comment by uwx** [comment]
Fixed by b40c29c821559db6fbb5eb96ebb7b800636a16f4
